### ISSUE TITLE
Problemas ao tentam reproduzir um conteúdo [LINUX]

### ISSUE THREAD

**Issue by kevinlucasilva** [imf4ll/moo#2]
Olá.

Eu adicionei uma música: https://www.youtube.com/watch?v=EXuslEZsrc4
![ksnip_20230720-083034](https://github.com/imf4ll/moo/assets/103600951/cfc26dd0-3e55-4733-8093-9f082d858e60)

E uma playlist: https://www.youtube.com/playlist?list=PLFW7HJ_xvmRcIZNiJVLY_dm1KrfFVRPfa
![ksnip_20230720-083806](https://github.com/imf4ll/moo/assets/103600951/bcadae4c-1c9a-4f7c-8f2e-18a922138015)

Elas foram adicionadas na barra lateral, mas, ao tentar reproduzí-las, ambas mostraram a mesma mensagem de erro:
![ksnip_20230720-083111](https://github.com/imf4ll/moo/assets/103600951/33cbcd88-13df-4fc9-a7dd-06b7a416e51c)

Assim que aparece essa mensagem a única alternativa foi fechar o programa. Essa é a saída no terminal:

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /search                   --> github.com/imf4ll/moo/backend/controllers.SearchController (4 handlers)
[GIN-debug] GET    /download                 --> github.com/imf4ll/moo/backend/controllers.DownloadController (4 handlers)
[GIN-debug] GET    /downloads                --> github.com/imf4ll/moo/backend/controllers.DownloadsController (4 handlers)
[GIN-debug] GET    /files                    --> github.com/imf4ll/moo/backend/controllers.ServeController (4 handlers)
[GIN-debug] GET    /playlist                 --> github.com/imf4ll/moo/backend/controllers.PlaylistController (5 handlers)
[GIN-debug] GET    /audio                    --> github.com/imf4ll/moo/backend/controllers.GetAudioController (5 handlers)
[GIN-debug] GET    /artist                   --> github.com/imf4ll/moo/backend/controllers.ArtistController (5 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :3001
```

Antes disso, a única coisa que eu havia feito foi definir uma pasta para os downloads.

Vale ressaltar também que aqui no Arch Linux eu tive que instalar o pacote `webkit2gtk` pois não estava abrindo, daí sanou a dependência.

**Comment by imf4ll** [comment]
A parte da música foi erro de sanitização minha, mas a playlist era pra salvar normalmente, você apertou "enter" na caixa de texto que vai a URL da playlist? Era pra aparecer também uma imagem de fundo com a thumbnail do primeiro vídeo da playlist, vou tentar reproduzir o erro depois pra corrigir.

**Comment by kevinlucasilva** [comment]
> A parte da música foi erro de sanitização minha, mas a playlist era pra salvar normalmente, você apertou "enter" na caixa de texto que vai a URL da playlist? Era pra aparecer também uma imagem de fundo com a thumbnail do primeiro vídeo da playlist, vou tentar reproduzir o erro depois pra corrigir.

Então, eu apenas colei a URL e adicionei um título e depois cliquei no botão de salvar.

Realmente também não apareceu uma thumbnail, se quiser dá pra criar outro *issue* sobre.

**Comment by imf4ll** [comment]
já entendi oq rolou, eu reproduzi o erro, era pra apertar enter dps de colar a URL mas na próxima atualização já vai ter isso consertado, quando colar uma playlist válida na caixa de texto a thumb vai aparecer automático e vai liberar salvar só após setar um título válido também, foi erro de sanitização por parte minha

**Comment by kevinlucasilva** [comment]
Beleza, fiz o que você falou e dei `ENTER` agora no campo de URL, daí carregou com a thumbnail:

![ksnip_20230720-101318](https://github.com/imf4ll/moo/assets/103600951/de59e5cd-8624-4738-a4a7-5e47e1e0622c)

E daí, a playslist foi adicionada e inclusive consigo ver as músicas contidas nela, que realmente são 10 faixas (https://www.youtube.com/playlist?list=PLRBp0Fe2Gpgk7Z7aku9SjrxHm37oWmVXf):
![ksnip_20230720-101331](https://github.com/imf4ll/moo/assets/103600951/7446e0cd-331c-40db-b53a-42adeb22b097)

Testei também com uma música separada (não dentro duma playlist), ou seja, uma URL do tipo *watch* (https://www.youtube.com/watch?v=dVteKLjhKFM&pp=ygUDbmNz) e não carregou:

![ksnip_20230720-101158](https://github.com/imf4ll/moo/assets/103600951/f30d0b98-cdf3-4a38-af4a-baf2d1f4836d)

Bem, disso eu entendi que o app carrega apenas playlists.

Enfim, seguindo, prontamente eu fui tentar reproduzir essa nova playlist adicionada (imagem 2), mas ao clicar sobre o botão de `Play` da playlist (ao lado do coração, imagem 2) o programa travou. Nisso o mouse ficou com ícone de **mão**, sabe? Aquele ícone de mão quando você às vezes tenta mover algo. Fui forçado a fecha o programa.

Bem, daí ao tentar abrí-lo novamente, aconteceu isso:

![Peek 2023-07-20 10-28](https://github.com/imf4ll/moo/assets/103600951/f2aeb036-1b5f-4e51-8848-c41e4ba54af6)

Então, agora não consigo clicar em nada, parece travado e não consigo interagir, e sou forçado a fechá-lo. Isso acontece todas as vezes que reabro. 😔

Aqui a saída:

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /search                   --> github.com/imf4ll/moo/backend/controllers.SearchController (4 handlers)
[GIN-debug] GET    /download                 --> github.com/imf4ll/moo/backend/controllers.DownloadController (4 handlers)
[GIN-debug] GET    /downloads                --> github.com/imf4ll/moo/backend/controllers.DownloadsController (4 handlers)
[GIN-debug] GET    /files                    --> github.com/imf4ll/moo/backend/controllers.ServeController (4 handlers)
[GIN-debug] GET    /playlist                 --> github.com/imf4ll/moo/backend/controllers.PlaylistController (5 handlers)
[GIN-debug] GET    /audio                    --> github.com/imf4ll/moo/backend/controllers.GetAudioController (5 handlers)
[GIN-debug] GET    /artist                   --> github.com/imf4ll/moo/backend/controllers.ArtistController (5 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :3001
[GIN] 2023/07/20 - 10:27:46 | 200 |     516.789µs |             ::1 | GET      "/audio?id=jK2aIUmmdP4"
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:12256): GLib-GObject-CRITICAL **: 10:27:46.643: invalid (NULL) pointer instance

(WebKitWebProcess:12256): GLib-GObject-CRITICAL **: 10:27:46.643: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Comment by imf4ll** [comment]
Quebrou por causa do erro de sanitização, vou criar uma opção nas configurações de dar wipe no local storage pra resolver esse tipo de problema, vou dar deploy nas correções quando terminar isso, daqui uns 10 minutos provavelmente

**Comment by imf4ll** [comment]
Tá upado a correção, qualquer problema só informar que vou dar o suporte necessário

**Comment by kevinlucasilva** [comment]
> Tá upado a correção, qualquer problema só informar que vou dar o suporte necessário

Testei a nova [versão](https://github.com/imf4ll/moo/releases/tag/v0.1.4-rc1) mas o problema que falei persiste:

> Então, agora não consigo clicar em nada, parece travado e não consigo interagir, e sou forçado a fechá-lo. Isso acontece todas as vezes que reabro. 😔

![Peek 2023-07-20 12-38](https://github.com/imf4ll/moo/assets/103600951/8e951cd3-7359-4bfb-8beb-8f657879c216)

Aqui a saída:

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /search                   --> github.com/imf4ll/moo/backend/controllers.SearchController (4 handlers)
[GIN-debug] GET    /download                 --> github.com/imf4ll/moo/backend/controllers.DownloadController (4 handlers)
[GIN-debug] GET    /downloads                --> github.com/imf4ll/moo/backend/controllers.DownloadsController (4 handlers)
[GIN-debug] GET    /files                    --> github.com/imf4ll/moo/backend/controllers.ServeController (4 handlers)
[GIN-debug] GET    /sync                     --> github.com/imf4ll/moo/backend/controllers.PlaylistController (4 handlers)
[GIN-debug] GET    /playlist                 --> github.com/imf4ll/moo/backend/controllers.PlaylistController (5 handlers)
[GIN-debug] GET    /audio                    --> github.com/imf4ll/moo/backend/controllers.GetAudioController (5 handlers)
[GIN-debug] GET    /artist                   --> github.com/imf4ll/moo/backend/controllers.ArtistController (5 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :3001
[GIN] 2023/07/20 - 12:30:58 | 200 |  355.134288ms |             ::1 | GET      "/audio?id=jK2aIUmmdP4"
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:21553): GLib-GObject-CRITICAL **: 12:30:58.813: invalid (NULL) pointer instance

(WebKitWebProcess:21553): GLib-GObject-CRITICAL **: 12:30:58.813: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Comment by imf4ll** [comment]
Agora é o bendito do autoaudiosink, eu tive que instalar ele tbm, vou ver aqui oq eu fiz e te passo

**Comment by imf4ll** [comment]
> Agora é o bendito do autoaudiosink, eu tive que instalar ele tbm, vou ver aqui oq eu fiz e te passo

 sudo pacman -S gstreamer gst-plugins-base-libs gst-plugins-base gst-plugins-bad-libs gst-libav gst-plugins-good

depois testa com "gst-launch-1.0 audiotestsrc ! autoaudiosink", se começar a tocar um som esquisito de fundo é pq deu certo

**Comment by kevinlucasilva** [comment]
> > Agora é o bendito do autoaudiosink, eu tive que instalar ele tbm, vou ver aqui oq eu fiz e te passo
> 
> sudo pacman -S gstreamer gst-plugins-base-libs gst-plugins-base gst-plugins-bad-libs gst-libav gst-plugins-good
> 
> depois testa com "gst-launch-1.0 audiotestsrc ! autoaudiosink", se começar a tocar um som esquisito de fundo é pq deu certo

Opa, funcionou agora! Estão reproduzindo. 👌
