### ISSUE TITLE
Botão de troca de tema aparentemente não funciona [LINUX]

### ISSUE THREAD

**Issue by kevinlucasilva** [imf4ll/moo#3]
Ao clicar sobre o botão nada acontece. Não sei bem se deveria acontecer, talvez ainda não tenha sido implementado algo relacionado à temas. Enfim, é isso. 🙂

![ksnip_20230720-084325](https://github.com/imf4ll/moo/assets/103600951/e1cef62a-44da-4a1b-b3d6-c09b272a6ae7)

**Comment by imf4ll** [comment]
É só um ícone de status, vou trocar o ícone dps pq realmente ficou confuso KKKK, quando tá a lua significa que não tem nenhum download em andamento, quando tem, aparece uma animaçãozinha

**Comment by kevinlucasilva** [comment]
> É só um ícone de status, vou trocar o ícone dps pq realmente ficou confuso KKKK, quando tá a lua significa que não tem nenhum download em andamento, quando tem, aparece uma animaçãozinha

LOL rsrrs eu achei que fosse uma lua e geralmente representa que é um tema noturno, né, algo do tipo 😅 

Inclusive, eu pairei o mouse sobre o ícone esperando alguma dica, né, tooltip, mas não apareceu nada e por isso eu achei que fosse isso.
