### ISSUE TITLE
Playslist não carrega [LINUX]

### ISSUE THREAD

**Issue by kevinlucasilva** [imf4ll/moo#4]
Estou tentando abrir uma playlist mas não tá rolando, mesmo tendo atualizado pra versão [v0.1.4-rc2](https://github.com/imf4ll/moo/releases/tag/v0.1.4-rc2).

![Peek 2023-07-20 15-51](https://github.com/imf4ll/moo/assets/103600951/b208f0f4-6975-4cce-8faf-bc4032262342)

**Comment by imf4ll** [comment]
pelo backend não tá rolando nem a requisição, provavelmente má formação do objeto quando foi salvo no local storage

**Comment by kevinlucasilva** [comment]
> pelo backend não tá rolando nem a requisição, provavelmente má formação do objeto quando foi salvo no local storage

A saída:

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /search                   --> github.com/imf4ll/moo/backend/controllers.SearchController (4 handlers)
[GIN-debug] GET    /download                 --> github.com/imf4ll/moo/backend/controllers.DownloadController (4 handlers)
[GIN-debug] GET    /downloads                --> github.com/imf4ll/moo/backend/controllers.DownloadsController (4 handlers)
[GIN-debug] GET    /files                    --> github.com/imf4ll/moo/backend/controllers.ServeController (4 handlers)
[GIN-debug] GET    /sync                     --> github.com/imf4ll/moo/backend/controllers.PlaylistController (4 handlers)
[GIN-debug] GET    /playlist                 --> github.com/imf4ll/moo/backend/controllers.PlaylistController (5 handlers)
[GIN-debug] GET    /audio                    --> github.com/imf4ll/moo/backend/controllers.GetAudioController (5 handlers)
[GIN-debug] GET    /artist                   --> github.com/imf4ll/moo/backend/controllers.ArtistController (5 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :3001
[GIN] 2023/07/20 - 15:55:46 | 200 |     678.875µs |             ::1 | GET      "/audio?id=n4tK7LYFxI0"
[GIN] 2023/07/20 - 15:55:47 | 400 |     329.928µs |             ::1 | GET      "/playlist?id=undefined"
```

Essa é uma playlist que adicionei antes da atualização. O mesmo acontece com essa outra aqui, só que outro erro:

![Peek 2023-07-20 15-57](https://github.com/imf4ll/moo/assets/103600951/d30f81cb-01e4-46ef-a82e-5b52f396457a)

**Comment by imf4ll** [comment]
como eu desconfiei, tá undefined pq a playlist foi mal formada antes de ir pro local storage, vc salvou como, foi na barra de pesquisa e favoritou ou adicionou manualmente?

**Comment by kevinlucasilva** [comment]
> como eu desconfiei, tá undefined pq a playlist foi mal formada antes de ir pro local storage, vc salvou como, foi na barra de pesquisa e favoritou ou adicionou manualmente?

Eu adicionei manualmente no botão de `+`

Eu não sei de usar "corretamente" o GitHub, pra criar sugestões o certo seria abrir um um **pull request**, né? Pois seria bom poder apagá-las.

**Comment by imf4ll** [comment]
Os pull requests não apagam tbm, vc tá usando o lugar certo, pull request é pra enviar uma implementação, issues são pra discutir, reportar bugs, etc

**Comment by imf4ll** [comment]
Eu vou tentar reproduzir alguma má formação de playlist pra ver se é problema no código ou erro por parte do webscrapping que as vezes falha e não tem oq fazer

**Comment by kevinlucasilva** [comment]
Eu até pensei em tentar apagar ou modificar algo em `~/.local/share/moo-linux-amd64`, mas são arquivos de banco de dados que não dão pra alterar 😅 ou pelo menos eu não sei como.

**Comment by imf4ll** [comment]
Fiquei curioso agora, no meu não tem isso aí não
